name: CI
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'GRDP Authorization Code'
        required: true
        default: 'paste your code here'
  
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Update
      run: |
         apt update
         apt install -y curl
    - name: Download Astra
      run: |
         curl -Lo /usr/bin/astra https://cesbo.com/astra-latest
         chmod +x /usr/bin/astra
    - name: Install Astra
      run: astra init
    - name: Launch Astra
      run: systemctl start astra
    - name: Launch Astra
      run: systemctl start astra
    - name: Install ngrok
      run: |
         sudo apt install snapd -y
         sudo snap install ngrok
    - name: Authtoken Ngrok
       run: ngrok authtoken 1nzweB7nWHf1sAZdFFztdGszCpC_5Y9oQxToZkCrv3zcgV8oa
    - name: Start Ngrok
       run: ngrok tcp -region ap 8000
    - name: Create SSH Access
      uses: mxschmitt/action-tmate@v3
