name: Ubuntu

on: workflow_dispatch

jobs:
  build:
  
    runs-on: ubuntu-20.04

    steps:
    - name: Update
      run: |
         sudo apt update
         sudo apt install -y curl
    - name: Download Astra
      run: |
         sudo curl -Lo /usr/bin/astra https://cesbo.com/astra-latest
         sudo chmod +x /usr/bin/astra
    - name: Install Astra
      run: sudo astra init
    - name: Launch Astra
      run: sudo systemctl start astra
    - name: Launch Astra
      run: sudo systemctl start astra
    - name: Install ngrok
      run: |
         sudo apt install snapd -y
         sudo snap install ngrok
    - name: Authtoken Ngrok
      run: ngrok authtoken $Env:NGROK_AUTH_TOKEN 
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: ddddddd
      run: cat /home/runner/.ngrok2/ngrok.yml
    - name: Start Ngrok
      run: ngrok tcp -region ap 8000
    - name: Create SSH Access
      uses: mxschmitt/action-tmate@v3
