name: Ubuntu

on: workflow_dispatch

jobs:
  build:
  
    runs-on: ubuntu-20.04

    steps:
    - name: Update
      run: |
         sudo apt update
         sudo apt install -y curl
    - name: Download Astra
      run: |
         sudo curl -Lo /usr/bin/astra https://cesbo.com/astra-latest
         sudo chmod +x /usr/bin/astra
    - name: Install Astra
      run: sudo astra init
    - name: Launch Astra
      run: sudo systemctl start astra
    - name: Launch Astra
      run: sudo systemctl start astra
    - name: Install ngrok
      run: |
         sudo curl -sLkO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz 
         tar xf ngrok-stable-linux-amd64.tgz
    - name: Authtoken Ngrok
      run: ./ngrok authtoken 27bMc4p9TnTpROBDdw8nVW5zOpb_5GscZGMoEqr2wQ7RUXLkn
    - name: Start Ngrok
      run: ./ngrok tcp -region ap 8000
    - name: Create SSH Access
      uses: mxschmitt/action-tmate@v3
